name: MATLAB Tests with Coverage
on: [push, pull_request]  # Trigger workflow on push or pull request events

jobs:
  test:  # Define a job named 'test'
    runs-on: ubuntu-latest  # Use GitHub-hosted Ubuntu runner
    steps:
      - name: Check out repository  # Step 1: Get your code
        uses: actions/checkout@v4
      
      - name: Set up MATLAB  # Step 2: Install MATLAB on the runner
        uses: matlab-actions/setup-matlab@v2
        with:
          products: MATLAB_Test  # Install MATLAB Test 
      # To generate the coverage view, use the version @3.1.0 of run-tests
      - name: Run tests with coverage  # Step 3: Run your tests and collect coverage
        uses: matlab-actions/run-tests@v3.1.0 
        with:
          code-coverage-metric-level: mcdc  # Generate coverage summary with mcdc metrics
